package com.SIEBS.ITCompany.model;

public enum Methods {
    GET_LOGIN_RESPONSE,
    GET_ALL_USERS,
    GET_ALL_PROJECTS,
    CREATE_PROJECT,
    GET_USER,
    UPDATE_USER,
    ADD_CV,
    ADD_SKILL,
    GET_ALL_SKILL,
    EDIT_SKILL,
    DOWNLOAD_CV,
    GET_MANAGER_PROJECTS,
    EDIT_JOB_DESCRIPTION,
    GET_EMPLOYEE_PROJECTS,
    EDIT_EMPLOYEE_ON_PROJECT

}
